export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum MemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  EXCUSED = 'EXCUSED',
}

export enum ServiceType {
  SUNDAY_SCHOOL = 'SUNDAY_SCHOOL',
  SUNDAY_SERVICE = 'SUNDAY_SERVICE',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  CONTACTED = 'CONTACTED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum FirstTimerFollowUpStatus {
  PENDING = 'PENDING',
  CONTACTED = 'CONTACTED',
  CONVERTED = 'CONVERTED',
  CLOSED = 'CLOSED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
}

export enum ChurchRole {
  MEMBER = 'MEMBER',
  WORKER = 'WORKER',
  MEN_LEADER = 'MEN_LEADER',
  WOMEN_LEADER = 'WOMEN_LEADER',
  YOUTH_LEADER = 'YOUTH_LEADER',
  DEACON = 'DEACON',
  DEACONESS = 'DEACONESS',
  ASSISTANT_PASTOR = 'ASSISTANT_PASTOR',
  PASTOR = 'PASTOR',
}

export enum Department {
  NONE = 'NONE',
  CHOIR = 'CHOIR',
  USHERING = 'USHERING',
  CHILDREN_MINISTRY = 'CHILDREN_MINISTRY',
  YOUTH_MINISTRY = 'YOUTH_MINISTRY',
  PRAYER_TEAM = 'PRAYER_TEAM',
  TECHNICAL = 'TECHNICAL',
  WELFARE = 'WELFARE',
  PROTOCOL = 'PROTOCOL',
  WORKERS_IN_TRAINING = 'WORKERS_IN_TRAINING',
}